markdown: rdiscount
appname: 'Github Tasks For Outlook'
appslogan: 'Emails into issues'
username: Code52
reponame: github-tasks-for-outlook
accent: "000000"
darkaccent: cacaca
description: 

feature1title: 'Create Issues Easily'
feature2title: 'We do the Heavy Lifting'
feature3title: 'More to Come'

feature1desc: 'Turn your emails into issues against your Github Repositories directly from Outlook'
feature2desc: 'Once you have linked to your account we fetch your repositories, users, milestones and labels.'
feature3desc: 'It''s an open source project, so you can always add yourself - but we have more planned to add in!'